// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsDevelopment {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQHD_aSK27FjrZuzm3mNpqTePK4OoDrBA',
    appId: '1:128354908204:web:467c4ec5e86cc05828b989',
    messagingSenderId: '128354908204',
    projectId: 'steve-dev-41d01',
    authDomain: 'steve-dev-41d01.firebaseapp.com',
    storageBucket: 'steve-dev-41d01.firebasestorage.app',
    measurementId: 'G-HZ785ZSN4Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdND7Bf5f_M2mhOl4-GETfkX0OvxZSWO0',
    appId: '1:128354908204:ios:81a4a91a099501c228b989',
    messagingSenderId: '128354908204',
    projectId: 'steve-dev-41d01',
    storageBucket: 'steve-dev-41d01.firebasestorage.app',
    iosClientId:
        '128354908204-j2ct8ecka8cth0sldtad4qg8vic9ed3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0S8mHftnPjbmHLuGEoe_WU8ixGCTv2Qs',
    appId: '1:128354908204:android:bc74940aace0f2b328b989',
    messagingSenderId: '128354908204',
    projectId: 'steve-dev-41d01',
    storageBucket: 'steve-dev-41d01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdND7Bf5f_M2mhOl4-GETfkX0OvxZSWO0',
    appId: '1:128354908204:ios:bdf4dc78db37099128b989',
    messagingSenderId: '128354908204',
    projectId: 'steve-dev-41d01',
    storageBucket: 'steve-dev-41d01.firebasestorage.app',
    iosClientId:
        '128354908204-cih642757f1hk4bihkorhlkmignfb3ak.apps.googleusercontent.com',
    iosBundleId: 'com.walturn.steve.dev',
  );
}
